services:
  frontend:
    image: frontend
    build:
      context: ./nodejs/frontend
      dockerfile: Dockerfile
    volumes:
      - ./nodejs/frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    restart: unless-stopped
    ports:
      - 5173:5173